// customers
export const GET_CUSTOMERS_REQUEST = "CUSTOMERS.GET_CUSTOMERS_REQUEST";
export const GET_CUSTOMERS_SUCCESS = "CUSTOMERS.GET_CUSTOMERS_SUCCESS";
export const GET_CUSTOMERS_FAILURE = "CUSTOMERS.GET_CUSTOMERS_FAILURE";
export const SAVE_CUSTOMER_REQUEST = "CUSTOMERS.SAVE_CUSTOMER_REQUEST";
export const SAVE_CUSTOMER_SUCCESS = "CUSTOMERS.SAVE_CUSTOMER_SUCCESS";
export const SAVE_CUSTOMER_FAILURE = "CUSTOMERS.SAVE_CUSTOMER_FAILURE";
export const TOGGLE_CUSTOMER_LOADER = "CUSTOMERS.TOGGLE_CUSTOMER_LOADER";
export const SET_SELECTED_CUSTOMER = "CUSTOMERS.SET_SELECTED_CUSTOMER";
export const DELETE_CUSTOMER_REQUEST = "CUSTOMERS.DELETE_CUSTOMER_REQUEST";
export const DELETE_CUSTOMER_SUCCESS = "CUSTOMERS.DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAILURE = "CUSTOMERS.DELETE_CUSTOMER_FAILURE";

// rightDrawer
export const TOGGLE_RIGHT_DRAWER = "DRAWER.TOGGLE_RIGHT_DRAWER";

// snackBar
export const TOGGLE_SNACKBAR = "SNACKBAR.TOGGLE_SNACKBAR";

// popup
export const TOGGLE_POPUP = "POPUP.TOGGLE_POPUP";

// products
export const GET_PRODUCTS_REQUEST = "PRODUCTS.GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "PRODUCTS.GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "PRODUCTS.GET_PRODUCTS_FAILURE";
export const SAVE_PRODUCT_REQUEST = "PRODUCTS.SAVE_PRODUCT_REQUEST";
export const SAVE_PRODUCT_SUCCESS = "PRODUCTS.SAVE_PRODUCT_SUCCESS";
export const SAVE_PRODUCT_FAILURE = "PRODUCTS.SAVE_PRODUCT_FAILURE";
export const TOGGLE_PRODUCT_LOADER = "PRODUCTS.TOGGLE_PRODUCT_LOADER";
export const SET_SELECTED_PRODUCT = "PRODUCTS.SET_SELECTED_PRODUCT";
export const DELETE_PRODUCT_REQUEST = "PRODUCTS.DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "PRODUCTS.DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "PRODUCTS.DELETE_PRODUCT_FAILURE";

// invoices
export const GET_INVOICES_REQUEST = "INVOICES.GET_INVOICES_REQUEST";
export const GET_INVOICES_SUCCESS = "INVOICES.GET_INVOICES_SUCCESS";
export const GET_INVOICES_FAILURE = "INVOICES.GET_INVOICES_FAILURE";
export const SAVE_INVOICE_REQUEST = "INVOICES.SAVE_INVOICE_REQUEST";
export const SAVE_INVOICE_SUCCESS = "INVOICES.SAVE_INVOICE_SUCCESS";
export const SAVE_INVOICE_FAILURE = "INVOICES.SAVE_INVOICE_FAILURE";
export const TOGGLE_INVOICE_LOADER = "INVOICES.TOGGLE_INVOICE_LOADER";
export const SET_SELECTED_INVOICE = "INVOICES.SET_SELECTED_INVOICE";
export const DELETE_INVOICE_REQUEST = "INVOICES.DELETE_INVOICE_REQUEST";
export const DELETE_INVOICE_SUCCESS = "INVOICES.DELETE_INVOICE_SUCCESS";
export const DELETE_INVOICE_FAILURE = "INVOICES.DELETE_INVOICE_FAILURE";

// invoice details
export const GET_INVOICE_DETAILS_REQUEST =
  "INVOICES.GET_INVOICE_DETAILS_REQUEST";
export const GET_INVOICE_DETAILS_SUCCESS =
  "INVOICES.GET_INVOICE_DETAILS_SUCCESS";
export const GET_INVOICE_DETAILS_FAILURE =
  "INVOICES.GET_INVOICE_DETAILS_FAILURE";

// stats
export const GET_STATS_REQUEST = "STATS.GET_STATS_REQUEST";
export const GET_STATS_SUCCESS = "STATS.GET_STATS_SUCCESS";
export const GET_STATS_FAILURE = "STATS.GET_STATS_FAILURE";
